baseURL = "http://machinly.cn/"
languageCode = "en-us"
title = "Machinly's Site"

[params] # theme parameters
    author = "Machinly"
    info = "Full Stack Engineer And Investor"
    description = "Machinly's personal website" # site description
    keywords = "blog,developer,investor" # site keywords

hideCredits = false
hideCopyright = false

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/machinly/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/machinly/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
